# ==========================================
# Filebeat 配置文件
# 云原生应用日志收集平台 - Docker 容器日志采集
# ==========================================

# ==========================================
# 1. 日志输入配置 (Inputs)
# ==========================================
filebeat.inputs:
  # 采集 Docker 容器标准输出 (stdout/stderr)
  - type: container
    enabled: true
    
    # Docker 容器日志路径
    paths:
      - '/var/lib/docker/containers/*/*.log'
    
    # ==========================================
    # JSON 解析配置
    # Docker 容器日志格式: {"log": "{JSON日志}", "stream": "stdout"}
    # 需要两次解析: 1) Docker包装 2) 应用JSON日志
    # 注意: Gunicorn 访问日志是文本格式,会被忽略
    # ==========================================
    json:
      keys_under_root: false        # 先保持 Docker 结构
      add_error_key: true           # 如果解析失败(如Gunicorn日志),添加错误字段
      message_key: log              # Docker 的 log 字段包含实际日志
      ignore_decoding_error: true   # 忽略非JSON日志(Gunicorn访问日志)
    
    # ==========================================
    # 多行日志合并配置 (Multiline)
    # Docker 容器日志已经是单行(JSON格式)
    # 不需要多行合并,注释掉以提高性能
    # ==========================================
    # multiline:
    #   type: pattern
    #   pattern: '^(\{|  File |  )'
    #   negate: false
    #   match: after
    #   max_lines: 500
    #   timeout: 10s
    
    # 容器过滤 - 只采集 web-app 容器的日志
    include_lines: ['.*']
    
    # 字段添加
    fields:
      log_source: docker_container
      collector: filebeat
      environment: production
    fields_under_root: true
    
    # ==========================================
    # 处理器配置 (Processors)
    # ==========================================
    processors:
      # 1. 添加 Docker 容器元数据（先添加，用于后续过滤）
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_fields: ["container.id"]
          labels.dedot: true
      
      # 2. 只保留 web-app 容器的日志（早期过滤，提高性能）
      - drop_event:
          when:
            not:
              contains:
                container.name: "elk-web-app"
      
      # 3. 解析 Docker log 字段中的 JSON 内容
      - decode_json_fields:
          fields: ["log"]
          target: "app"             # 提取到 app 命名空间，避免冲突
          overwrite_keys: false
          add_error_key: true
          max_depth: 3              # 支持嵌套 JSON (exception对象)
          process_array: false
      
      # 4. 检测日志类型并打标签
      - script:
          lang: javascript
          source: >
            function process(event) {
              var log = event.Get("log");
              if (!log) return;
              
              // 检测是否是 JSON 格式的应用日志
              if (log.trim().startsWith("{") && event.Get("app.timestamp")) {
                event.Put("log_type", "application");
              }
              // 检测是否是 Gunicorn 访问日志
              else if (log.match(/^\d+\.\d+\.\d+\.\d+/) || log.includes("GET ") || log.includes("POST ")) {
                event.Put("log_type", "gunicorn_access");
              }
              // 其他类型
              else {
                event.Put("log_type", "other");
              }
            }
      
      # 5. 处理应用 JSON 日志 - 提升到根级别
      - script:
          lang: javascript
          when:
            equals:
              log_type: "application"
          source: >
            function process(event) {
              // 将 app 命名空间下的字段提升到根级别
              var appFields = event.Get("app");
              if (!appFields) return;
              
              for (var key in appFields) {
                if (appFields.hasOwnProperty(key)) {
                  event.Put(key, appFields[key]);
                }
              }
              
              // 保留 level 字段的同时也创建 log.level（兼容 ECS）
              var level = event.Get("level");
              if (level) {
                event.Put("log.level", level);
              }
            }
      
      # 6. 解析 Gunicorn 访问日志（纯文本格式）
      - dissect:
          when:
            equals:
              log_type: "gunicorn_access"
          tokenizer: '%{client_ip} - - [%{timestamp}] "%{http_method} %{url} %{http_version}" %{status_code} %{response_size}'
          field: "log"
          target_prefix: "gunicorn"
          ignore_failure: true
      
      # 7. 为 Gunicorn 日志添加标准字段
      - script:
          lang: javascript
          when:
            equals:
              log_type: "gunicorn_access"
          source: >
            function process(event) {
              event.Put("level", "INFO");
              event.Put("log.level", "INFO");
              event.Put("logger", "gunicorn");
              event.Put("message", event.Get("log"));
              
              // 转换状态码为数字
              var statusCode = event.Get("gunicorn.status_code");
              if (statusCode) {
                event.Put("http.response.status_code", parseInt(statusCode));
                event.Put("status_code", parseInt(statusCode));
              }
              
              // 复制 HTTP 相关字段
              var method = event.Get("gunicorn.http_method");
              if (method) {
                event.Put("http.request.method", method);
                event.Put("http_method", method);
              }
              
              var url = event.Get("gunicorn.url");
              if (url) {
                event.Put("url.path", url);
                event.Put("url", url);
              }
            }
      
      # 8. 添加主机元数据
      - add_host_metadata:
          netinfo.enabled: true
          cache.ttl: 5m
      
      # 9. 解析应用日志的时间戳 (支持微秒精度)
      - timestamp:
          field: timestamp
          layouts:
            - '2006-01-02T15:04:05.999999999Z'  # 纳秒精度
            - '2006-01-02T15:04:05.999999Z'     # 微秒精度
            - '2006-01-02T15:04:05.999Z'        # 毫秒精度
            - '2006-01-02T15:04:05Z'            # 秒精度
          ignore_missing: true
          ignore_failure: true
      
      # 10. 解析 Gunicorn 时间戳
      - timestamp:
          when:
            equals:
              log_type: "gunicorn_access"
          field: gunicorn.timestamp
          layouts:
            - '02/Jan/2006:15:04:05 -0700'
            - '02/Jan/2006:15:04:05'
          ignore_missing: true
          ignore_failure: true
      
      # 11. 删除 Docker 包装字段和冗余字段
      - drop_fields:
          fields:
            - "log"                    # Docker 包装的原始字段（已解析）
            - "stream"                 # Docker stream 字段
            - "app"                    # 临时命名空间（已提升）
            - "agent.ephemeral_id"
            - "agent.id"
            - "ecs.version"
            - "input.type"
          ignore_missing: true

# ==========================================
# 2. 输出配置 - 发送到 Logstash
# ==========================================
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  worker: 2
  bulk_max_size: 2048
  compression_level: 3

# ==========================================
# 3. 日志配置
# ==========================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7

# ==========================================
# 4. HTTP 端点配置
# ==========================================
http:
  enabled: true
  host: "0.0.0.0"
  port: 5066
