# ==========================================
# Filebeat 配置文件
# 云原生应用日志收集平台 - Docker 容器日志采集
# ==========================================

# ==========================================
# 1. 日志输入配置 (Inputs)
# ==========================================
filebeat.inputs:
  # 采集 Docker 容器标准输出 (stdout/stderr)
  - type: filestream
    enabled: true
    
    # Docker 容器日志路径
    paths:
      - '/var/lib/docker/containers/*/*.log'
    
    parsers:
      - container:
          stream: all         # stdout 和 stderr
          format: auto        # 自动检测格式
    
    # 字段添加
    fields:
      log_source: docker_container
      collector: filebeat
      environment: production
    fields_under_root: true
    
    # ==========================================
    # 处理器配置 (Processors)
    # ==========================================
    processors:
      # 1. 添加 Docker 容器元数据
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_fields: ["container.id"]
          labels.dedot: true
      
      # 2. 保留 web-app 容器的日志
      - drop_event:
          when:
            not:
              contains:
                container.name: "elk-web-app"
      
      # 3. 检测日志类型并打标签
      - script:
          lang: javascript
          source: >
            function process(event) {
              var msg = event.Get("message");
              if (!msg) return;
              
              // 去除空白字符
              var trimmed = msg.replace(/^\s+|\s+$/g, '');
              
              // 检测是否是 JSON 格式的应用日志(以 { 开头)
              if (trimmed.charAt(0) === '{') {
                event.Put("log_type", "application");
              }
              // 检测是否是 Gunicorn 访问日志 (IP地址开头)
              else if (/^\d+\.\d+\.\d+\.\d+/.test(msg) || msg.indexOf("GET ") !== -1 || msg.indexOf("POST ") !== -1) {
                event.Put("log_type", "gunicorn_access");
              }
              // 其他类型
              else {
                event.Put("log_type", "other");
              }
            }
      
      # 4. 解析应用层 JSON 日志(仅对 application 类型)
      - decode_json_fields:
          when:
            equals:
              log_type: "application"
          fields: ["message"]
          target: "app"
          overwrite_keys: false
          add_error_key: true
          max_depth: 3
          process_array: false
      
      # 5. 处理应用 JSON 日志 - 提升到根级别
      - script:
          lang: javascript
          when:
            equals:
              log_type: "application"
          source: >
            function process(event) {
              // 将 app 命名空间下的字段提升到根级别
              var appFields = event.Get("app");
              if (!appFields) return;
              
              for (var key in appFields) {
                if (appFields.hasOwnProperty(key)) {
                  event.Put(key, appFields[key]);
                }
              }
              
              // 保留 level 字段的同时也创建 log.level（兼容 ECS）
              var level = event.Get("level");
              if (level) {
                event.Put("log.level", level);
              }
            }
      
      # 6. 解析 Gunicorn 访问日志（纯文本格式）
      - dissect:
          when:
            equals:
              log_type: "gunicorn_access"
          tokenizer: '%{client_ip} - - [%{timestamp}] "%{http_method} %{url} %{http_version}" %{status_code} %{response_size}'
          field: "message" 
          target_prefix: "gunicorn"
          ignore_failure: true
      
      # 7. 为 Gunicorn 日志添加标准字段
      - script:
          lang: javascript
          when:
            equals:
              log_type: "gunicorn_access"
          source: >
            function process(event) {
              event.Put("level", "INFO");
              event.Put("log.level", "INFO");
              event.Put("logger", "gunicorn");
              // message 字段已存在，不需要重新设置
              
              // 转换状态码为数字
              var statusCode = event.Get("gunicorn.status_code");
              if (statusCode) {
                event.Put("http.response.status_code", parseInt(statusCode));
                event.Put("status_code", parseInt(statusCode));
              }
              
              // 复制 HTTP 相关字段
              var method = event.Get("gunicorn.http_method");
              if (method) {
                event.Put("http.request.method", method);
                event.Put("http_method", method);
              }
              
              var url = event.Get("gunicorn.url");
              if (url) {
                event.Put("url.path", url);
                event.Put("url", url);
              }
            }
      
      # 8. 添加主机元数据
      - add_host_metadata:
          netinfo.enabled: true
          cache.ttl: 5m
      
      # 9. 解析应用日志的时间戳
      - timestamp:
          field: timestamp
          layouts:
            - '2006-01-02T15:04:05.999999999Z'  # 纳秒精度
            - '2006-01-02T15:04:05.999999Z'     # 微秒精度
            - '2006-01-02T15:04:05.999Z'        # 毫秒精度
            - '2006-01-02T15:04:05Z'            # 秒精度
          ignore_missing: true
          ignore_failure: true
      
      # 10. 解析 Gunicorn 时间戳
      - timestamp:
          when:
            equals:
              log_type: "gunicorn_access"
          field: gunicorn.timestamp
          layouts:
            - '02/Jan/2006:15:04:05 -0700'
            - '02/Jan/2006:15:04:05'
          ignore_missing: true
          ignore_failure: true
      
      # 11. 添加指纹（用于去重）
      - fingerprint:
          fields: ["timestamp", "level", "container.id"]
          target_field: "@metadata.fingerprint"
          method: "sha256"
          ignore_missing: true
      
      # 12. 删除冗余字段
      - drop_fields:
          fields:
            - "app"                    # 临时命名空间
            - "agent.ephemeral_id"
            - "agent.id"
            - "ecs.version"
            - "input.type"
            - "log.offset"            
            - "log.file.path"          
          ignore_missing: true

# ==========================================
# 2. 输出配置 - 发送到 Logstash
# ==========================================
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  worker: 2
  bulk_max_size: 2048
  compression_level: 3

# ==========================================
# 3. 日志配置
# ==========================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7

# ==========================================
# 4. HTTP 端点配置
# ==========================================
http:
  enabled: true
  host: "0.0.0.0"
  port: 5066
